import http from "node:http";
const port=3199;
const host="127.0.0.1";
const verifyToken="RF_DRYRUN_VERIFY_TOKEN";
function send(res,status,body,type="application/json"){res.writeHead(status,{"Content-Type":type});res.end(body);}
function hashId(v){let h=0;for(const c of String(v||"")){h=((h<<5)-h)+c.charCodeAt(0);h|=0;}return "hash_"+Math.abs(h);}
function normalize(payload){const msg=payload?.entry?.[0]?.changes?.[0]?.value?.messages?.[0]||{};const text=msg?.text?.body||"";return {rf_schema:"rf.whatsapp.inbound_message.v1",received_at:new Date().toISOString(),channel:"whatsapp",from_hash:hashId(msg.from),message_id:msg.id||"PENDING_MESSAGE_ID",type:msg.type||"text",text,route:text.startsWith("/help")?"help":"chat_local_ai",trace_id:"rf_wa_echo_"+Date.now(),policy:"DRYRUN_ONLY_NO_SHELL"};}
function reply(to,body){return {messaging_product:"whatsapp",to,type:"text",text:{body}};}
const server=http.createServer((req,res)=>{const u=new URL(req.url,`http://${host}:${port}`);if(req.method==="GET"&&u.pathname==="/webhooks/whatsapp"){const mode=u.searchParams.get("hub.mode");const token=u.searchParams.get("hub.verify_token");const challenge=u.searchParams.get("hub.challenge");if(mode==="subscribe"&&token===verifyToken){return send(res,200,challenge||"","text/plain");}return send(res,403,"FORBIDDEN","text/plain");}if(req.method==="POST"&&u.pathname==="/webhooks/whatsapp"){let raw="";req.on("data",c=>raw+=c);req.on("end",()=>{let payload={};try{payload=JSON.parse(raw||"{}");}catch{}const normalized=normalize(payload);return send(res,200,JSON.stringify({ok:true,normalized,dryrun_reply:reply("DRYRUN_TO","RF_WHATSAPP_ECHO_OK"),real_send:"NO_REAL_SEND"},null,2));});return;}return send(res,404,"NOT_FOUND","text/plain");});
server.listen(port,host,async()=>{const base=`http://${host}:${port}`;const getRes=await fetch(`${base}/webhooks/whatsapp?hub.mode=subscribe&hub.verify_token=${verifyToken}&hub.challenge=RF_CHALLENGE_OK`);const challenge=await getRes.text();const sample={entry:[{changes:[{value:{messages:[{id:"wamid.DRYRUN",from:"5210000000000",type:"text",text:{body:"/help"}}]}}]}]};const postRes=await fetch(`${base}/webhooks/whatsapp`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(sample)});const postJson=await postRes.json();console.log(JSON.stringify({rf_schema:"rf.whatsapp.webhook.echo.result.v1",estado:"RF_WHATSAPP_WEBHOOK_ECHO_OK",created_at:new Date().toISOString(),server:`${host}:${port}`,verify_status:getRes.status,verify_challenge:challenge,post_status:postRes.status,normalized:postJson.normalized,dryrun_reply:postJson.dryrun_reply,backend:"NO_TOCADO",pm2:"NO_TOCADO",firewall:"NO_TOCADO",real_whatsapp_send:"NO_REAL_SEND",siguiente:"RF_WHATSAPP_SEND_DRYRUN_V1"},null,2));server.close();});
