services:
  headscale:
    image: headscale/headscale:v0.25.1
    container_name: headscale
    command: serve
    volumes:
            - ./config:/etc/headscale
            - ./data:/etc/headscale/data
    ports:
            - "8080:8080"
            - "9090:9090"
    restart: unless-stopped
  headscale-ui:
    image: goodieshq/headscale-admin:latest
    container_name: headscale-ui
    ports:
            - "3001:3000"
    environment:
            - HEADSCALE_URL=http://localhost:8080
    restart: unless-stopped
